<?php
ini_set('display_errors', 0);
    require 'vendor/autoload.php';
    require '_ini_.php';
    require '_library_/_includes_/config.php';
    require '_library_/_includes_/app_config.inc';
    $skeleton=new _classes_\skeleton();
    $help=new _classes_\helpers();
?>

<?php require '_library_/_includes_/header.inc'; ?>
<div>
    <?php require '_library_/_includes_/menu.inc'; ?>
</div>
<!-- END HEADER -->
<!-- BEGIN PAGE CONTAINER -->
<div class="page-container">
	<!-- BEGIN PAGE HEAD -->
	<div class="page-head">
		<div class="container">
			<!-- BEGIN PAGE TITLE -->
			<div class="page-title">
				 
			</div>
			<!-- END PAGE TITLE -->
			<!-- BEGIN PAGE TOOLBAR -->
			<div class="page-toolbar">
				 
			</div>
			<!-- END PAGE TOOLBAR -->
		</div>
	</div>
	<!-- END PAGE HEAD -->
	<!-- BEGIN PAGE CONTENT -->
	<div class="page-content">
		<div class="container">
			 
			 
			<!-- END PAGE BREADCRUMB -->
			<!-- BEGIN PAGE CONTENT INNER -->
			<div class="row">
				<div class="col-md-12">
					<div class="note note-success note-bordered">
						<p>
							 Please conform to all ethics and standards.
						</p>
					</div>
					 <div class="newsitem_text">
                                                      
                                                
                                        
                                             <p><center><img src="assets/logo.png" width="110" height="120"/></center></p>
                                         <center><p ><h4 style="font-weight:bolder">STANDARDS AND ETHICS</h4></p></center>
                                         <u></u>
                                        <hr>
                                <p>All Ghanaian applicants for the 2015/2016 Academic year admission are required to use Takoradi Polytechnic online admission portal. The procedure for the online application process is as follows:</p>
                                <p><strong style="line-height: 12.0000009536743px;">I. </strong><span style="line-height: 12.0000009536743px;">Applicants are required to purchase Takoradi Polytechnic and  Allied Sciences E-Vouchers at </span><strong style="line-height: 12.0000009536743px;">GHC170.00</strong><span style="line-height: 12.0000009536743px;"> from any branch of the following banks:</span><span style="line-height: 12.0000009536743px;">                                                                                              </span></p>
                                <ul>
                                <li style="text-align: left;"><strong style="line-height: 12.0000009536743px;">Ghana Commercial Bank (GCB) or</strong></li>
                                <li style="text-align: left;"><strong style="line-height: 12.0000009536743px;">Agricultural Development Bank (adb) or</strong></li>
                                <li style="text-align: left;"><strong style="line-height: 12.0000009536743px;">Zenith Bank</strong></li>
                                </ul>
                                <p><strong>II. </strong>Upon payment E - Voucher which contains a PIN and SERIAL NUMBER will be generated by the bank which will be required in completing the online form.</p>
                                <p><strong>III. </strong>Access the online form by visiting our online admission portal at tpolyonline.com/Admissions</p>
                                <p><strong>IV</strong>. In completing the online form, applicants will be required to upload their passport size photograph (not more than 20KB) with a white background.</p>
                                <p><strong>V. </strong>Applicants are advised to check thoroughly all details entered before they finally submit their online applications. A form, once submitted, can be viewed, but cannot be edited.</p>
                                <p><strong>VI.</strong> Applicants should print out application summary; attach result slips,certificates (WASSCE/SSSCE)or Certificates(Top and Access Course) and all other relevant documents. These documents   should be submitted in triplicates (three (3) copies each) to the Registrar.</p>
                                <p><strong>VII. </strong>The application documents as specified (VI) above should be put in any decent envelope and be posted by any fast and reliable means to</p>
                               <hr>
                               <p align="center"><i>Signed</i></p>
                               <p align="center"><i><strong>The Registrar</strong></i></p>
                                           <p align="center"><i><strong>Takoradi Polytechnic</i></strong></p>
                                
                                <p><strong> </strong></p>
                                
                                 
                                 
                                        </div>
				</div>
			</div>
			<!-- END PAGE CONTENT INNER -->
		</div>
	</div>
	<!-- END PAGE CONTENT -->
</div>
<!-- END PAGE CONTAINER -->
 
<!-- BEGIN FOOTER -->
<div class="page-footer" style="">
	<div class="container">
            <center><?php echo $help->copyright(); ?></center>
	</div>
</div>
<div class="scroll-to-top">
	<i class="icon-arrow-up"></i>
</div>

 <?php include("_library_/_includes_/scripts.php");  ?>

</html>